# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
workspace 'iOS-Engineering.xcworkspace'
target 'iOS-Engineering' do

    
#    pod 'AFNetworking', :path => '~/.cocoapods/repos/SNEBuy_repos/AFNetworking/2.5.5'
    pod "CTMediator"
    pod "Objection"
    pod "SDWebImage"
    
    
    target 'DynamicLib' do
       project '../DynamicFramework/DynamicLib/DynamicLib.xcodeproj'
    end
    
    target 'StaticFramework' do
        project '../StaticFramework/StaticFramework/StaticFramework.xcodeproj'
    end

    # Common 作为一个独立的静态库被依赖
    # 需要1.增加依赖(Frameworks,Libraries...中添加)
    #    2.build phases 中暴露头文件
    #    3.Common.h 引入要暴露的类
    target 'Common' do
      project 'Common/Common.xcodeproj'
    end
  target 'iOS-EngineeringTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS-EngineeringUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
