# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
workspace 'iOS-Engineering.xcworkspace'
target 'iOS-Engineering' do

    
#    pod 'AFNetworking', :path => '~/.cocoapods/repos/SNEBuy_repos/AFNetworking/2.5.5'
    pod "CTMediator"
    
    
    
    
    target 'DynamicLib' do
       project '../DynamicFramework/DynamicLib/DynamicLib.xcodeproj'
    end
    
    target 'StaticFramework' do
        project '../StaticFramework/StaticFramework/StaticFramework.xcodeproj'
    end

  target 'iOS-EngineeringTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS-EngineeringUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
